import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.1";
import { sendEmail, getEmailConfig } from "../send-alert-email/email-service.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

interface ApprovalEmailRequest {
  providerId: string;
  providerEmail: string;
  businessName: string;
  password?: string; // Optional password if auto-generated by admin
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseServiceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    if (!supabaseServiceKey) {
      console.error("[send-provider-approval-email] SUPABASE_SERVICE_ROLE_KEY is not set");
      return new Response(
        JSON.stringify({ error: "Internal Configuration Error" }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    // ✅ FIX: Verify admin authentication
    const authHeader = req.headers.get("Authorization");
    if (!authHeader) {
      console.error("[send-provider-approval-email] No Authorization header provided");
      return new Response(
        JSON.stringify({ error: "Unauthorized: No authorization header" }),
        { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const token = authHeader.replace("Bearer ", "").trim();
    const { data: { user }, error: authError } = await supabase.auth.getUser(token);

    if (authError || !user) {
      console.error("[send-provider-approval-email] Auth error:", authError);
      return new Response(
        JSON.stringify({ error: "Unauthorized: Invalid token" }),
        { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Check if user is admin
    const { data: isAdmin } = await supabase.rpc('has_role', {
      _user_id: user.id,
      _role: 'admin'
    });

    if (!isAdmin) {
      // Fallback check
      const { data: userRole } = await supabase
        .from("user_roles")
        .select("role")
        .eq("user_id", user.id)
        .eq("role", "admin")
        .maybeSingle();

      if (!userRole) {
        return new Response(
          JSON.stringify({ error: "Only admins can send approval emails" }),
          { status: 403, headers: { "Content-Type": "application/json", ...corsHeaders } }
        );
      }
    }

    const emailConfig = getEmailConfig();
    if (!emailConfig) {
      console.error("Missing Gmail credentials");
      return new Response(
        JSON.stringify({ error: "Email service not configured" }),
        { status: 500, headers: { "Content-Type": "application/json", ...corsHeaders } }
      );
    }

    const { providerId, providerEmail, businessName, password }: ApprovalEmailRequest = await req.json();

    console.log(`Sending approval email to provider: ${providerEmail}`);

    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseServiceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    // Get provider details
    const { data: provider, error: providerError } = await supabase
      .from("service_providers")
      .select("user_id, business_name")
      .eq("id", providerId)
      .single();

    if (providerError || !provider) {
      throw new Error(`Provider not found: ${providerError?.message}`);
    }

    // Get user email from auth
    const { data: user, error: userError } = await supabase.auth.admin.getUserById(provider.user_id);

    if (userError || !user.user) {
      throw new Error(`User not found: ${userError?.message}`);
    }

    const loginUrl = `${Deno.env.get("PUBLIC_APP_URL") || "https://app.fleethub.com"}/login`;
    const dashboardUrl = `${Deno.env.get("PUBLIC_APP_URL") || "https://app.fleethub.com"}/partner/dashboard`;

    // Email content
    const emailHtml = `
      <div style="max-width: 600px; margin: 0 auto;">
        <h2 style="color: #1f2937; margin-bottom: 16px;">Congratulations! Your Profile is Approved</h2>
        
        <p style="color: #4b5563; line-height: 1.6; margin-bottom: 16px;">
          Great news! Your service provider profile for <strong>${businessName}</strong> has been approved and is now live on the Fleet Directory.
        </p>

        <div style="background-color: #f3f4f6; border-left: 4px solid #3b82f6; padding: 16px; margin: 24px 0; border-radius: 4px;">
          <p style="margin: 0; color: #1f2937; font-weight: 600;">Next Steps:</p>
          <ol style="margin: 8px 0 0 0; padding-left: 20px; color: #4b5563;">
            <li>Log in to your Partner Dashboard</li>
            <li>Complete your profile (add logo, description, location, perks)</li>
            <li>Start receiving booking requests from fleet users</li>
          </ol>
        </div>

        <div style="margin: 32px 0; text-align: center;">
          <a href="${loginUrl}" 
             style="display: inline-block; background-color: #3b82f6; color: #ffffff; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-weight: 600;">
            Log In to Partner Dashboard
          </a>
        </div>

        <p style="color: #6b7280; font-size: 14px; margin-top: 24px;">
          <strong>Login Credentials:</strong><br>
          Email: ${user.user.email}<br>
          ${password ? `Password: <strong>${password}</strong><br><br><em style="color: #dc2626;">Please save this password securely. You can change it after logging in.</em>` : 'Use the password you set during registration, or reset it from the login page if needed.'}
        </p>

        ${!password ? `
        <p style="color: #6b7280; font-size: 14px; margin-top: 16px;">
          If you forgot your password, you can reset it from the login page.
        </p>
        ` : ''}

        <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 32px 0;">

        <p style="color: #9ca3af; font-size: 12px; margin: 0;">
          This is an automated email from MyMoto Fleet Management System.<br>
          If you have any questions, please contact our support team.
        </p>
      </div>
    `;

    await sendEmail({
      to: providerEmail,
      subject: `Your Fleet Directory Profile is Approved! - ${businessName}`,
      html: emailHtml,
    });

    console.log(`Approval email sent successfully to ${providerEmail}`);

    return new Response(
      JSON.stringify({ success: true, message: "Approval email sent successfully" }),
      { status: 200, headers: { "Content-Type": "application/json", ...corsHeaders } }
    );
  } catch (error: any) {
    console.error("Error sending approval email:", error);
    return new Response(
      JSON.stringify({ error: error.message || "Failed to send approval email" }),
      { status: 500, headers: { "Content-Type": "application/json", ...corsHeaders } }
    );
  }
});
