/// <reference lib="deno.ns" />
import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.1";
import { sendEmail, getEmailConfig, EmailTemplates } from "../_shared/email-service.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

interface ApprovalEmailRequest {
  providerId: string;
  providerEmail: string;
  businessName: string;
  password?: string; // Optional password if auto-generated by admin
}

serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseServiceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    if (!supabaseServiceKey) {
      console.error("[send-provider-approval-email] SUPABASE_SERVICE_ROLE_KEY is not set");
      return new Response(
        JSON.stringify({ error: "Internal Configuration Error" }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    // Verify admin authentication
    const authHeader = req.headers.get("Authorization");
    if (!authHeader) {
      console.error("[send-provider-approval-email] No Authorization header provided");
      return new Response(
        JSON.stringify({ error: "Unauthorized: No authorization header" }),
        { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const token = authHeader.replace("Bearer ", "").trim();
    const { data: { user }, error: authError } = await supabase.auth.getUser(token);

    if (authError || !user) {
      console.error("[send-provider-approval-email] Auth error:", authError);
      return new Response(
        JSON.stringify({ error: "Unauthorized: Invalid token" }),
        { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Check if user is admin
    const { data: isAdmin } = await supabase.rpc('has_role', {
      _user_id: user.id,
      _role: 'admin'
    });

    if (!isAdmin) {
      // Fallback check
      const { data: userRole } = await supabase
        .from("user_roles")
        .select("role")
        .eq("user_id", user.id)
        .eq("role", "admin")
        .maybeSingle();

      if (!userRole) {
        return new Response(
          JSON.stringify({ error: "Only admins can send approval emails" }),
          { status: 403, headers: { "Content-Type": "application/json", ...corsHeaders } }
        );
      }
    }

    const emailConfig = getEmailConfig();
    if (!emailConfig) {
      console.error("Missing Gmail credentials");
      return new Response(
        JSON.stringify({ error: "Email service not configured" }),
        { status: 500, headers: { "Content-Type": "application/json", ...corsHeaders } }
      );
    }

    const { providerId, providerEmail, businessName, password }: ApprovalEmailRequest = await req.json();

    console.log(`Sending approval email to provider: ${providerEmail}`);

    // Get provider details (if needed again, but we have data from request)
    // Double check provider exists to be safe
    const { data: provider, error: providerError } = await supabase
      .from("service_providers")
      .select("user_id, business_name")
      .eq("id", providerId)
      .single();

    if (providerError || !provider) {
      throw new Error(`Provider not found: ${providerError?.message}`);
    }

    // Get user email from auth
    const { data: providerUser, error: userError } = await supabase.auth.admin.getUserById(provider.user_id);

    if (userError || !providerUser.user) {
      throw new Error(`User not found: ${userError?.message}`);
    }

    const loginUrl = `${Deno.env.get("PUBLIC_APP_URL") || "https://mymotofleet.com"}/auth`;
    
    const emailTemplate = EmailTemplates.providerApproval({
      businessName: businessName,
      loginUrl: loginUrl,
      password: password
    });

    await sendEmail({
      to: providerEmail,
      subject: emailTemplate.subject,
      html: emailTemplate.html,
    });

    console.log(`Approval email sent successfully to ${providerEmail}`);

    return new Response(
      JSON.stringify({ success: true, message: "Approval email sent successfully" }),
      { status: 200, headers: { "Content-Type": "application/json", ...corsHeaders } }
    );
  } catch (error: any) {
    console.error("Error sending approval email:", error);
    return new Response(
      JSON.stringify({ error: error.message || "Failed to send approval email" }),
      { status: 500, headers: { "Content-Type": "application/json", ...corsHeaders } }
    );
  }
});
